//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B3.Investimentos.Application {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensApplication {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public MensagensApplication() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("B3.Investimentos.Application.MensagensApplication", typeof(MensagensApplication).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CdbValorInicialInvalido {
            get {
                return ResourceManager.GetString("CdbValorInicialInvalido", resourceCulture);
            }
        }
        
        public static string CdbPrazoEmMesesInvalido {
            get {
                return ResourceManager.GetString("CdbPrazoEmMesesInvalido", resourceCulture);
            }
        }
        
        public static string FalhasDeValidacaoEncontradas {
            get {
                return ResourceManager.GetString("FalhasDeValidacaoEncontradas", resourceCulture);
            }
        }
        
        public static string FalhaNoProcessamentoDaRequisicao {
            get {
                return ResourceManager.GetString("FalhaNoProcessamentoDaRequisicao", resourceCulture);
            }
        }
        
        public static string CdbPercentualCdiInvalido {
            get {
                return ResourceManager.GetString("CdbPercentualCdiInvalido", resourceCulture);
            }
        }
        
        public static string CdbPercentualCdiPagoPeloBancoInvalido {
            get {
                return ResourceManager.GetString("CdbPercentualCdiPagoPeloBancoInvalido", resourceCulture);
            }
        }
    }
}
